### ISSUE TITLE
Support Server side filtering

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/remote-settings#88] opened 2018-09-18 14:35 UTC
Currently we sync an entire collection.  This issue is to track discussion about also supporting server side filtering.  It might help in situations where we publish many records in a collection but a client only requires one of them, due to locale or some other filtering. 

Server side filtering requires a lot more thought on whether this is what we actually want.  Let's collect things that should be considered in this issue.

**Comment by leplatrem** [comment] 2018-09-18 19:42
This was brought several times but we never had a good solution for signature verification.
Should the server compute a signature for each combination of filters? Are they known in advance? Is it acceptable to compute the signature on the fly for each response?

**Comment by mostlygeek** [comment] 2018-09-19 17:12
JEXL is a client side library and javascript-ish.  Porting that to python and having it work exactly like the client would be challenging.  The matching context would have to be part of the request, etc.

**Comment by leplatrem** [comment] 2018-09-20 11:00
> JEXL is a client side library and javascript-ish. Porting that to python and having it work exactly like the client would be challenging. The matching context would have to be part of the request, etc.

That's an additional challenge indeed, but that could be technically be solved in theory.

The signature one is more architecture/security design issue that I don't know how to masticate ;)

**Comment by mostlygeek** [comment] 2018-09-20 20:46
re: signing ... 

Not sure if autograph is set up for it.  We could generate a payload and sign it.  It's just more load on autograph but that's mostly stateless (afaik) so it's really a scaling problem?

**Comment by leplatrem** [comment] 2018-09-21 08:33
> Not sure if autograph is set up for it. We could generate a payload and sign it. It's just more load on autograph but that's mostly stateless (afaik) so it's really a scaling problem?

We would sign each payload and serve the obtained signature with each response for example?

**Comment by leplatrem** [comment] 2018-09-21 08:51
Let's go back to what we're trying to solve. 

>  It might help in situations where we publish many records in a collection but a client only requires one of them, due to locale or some other filtering.

Let's say we have 1000 records and only one picked based on JEXL filters. 

- Worst scenario: the 1000 records are frequently updated, the whole collection is re-downloaded each time it changes, but only one record is used. How much data does it represent? Hundreds of kilobytes?
- If data does not change much: a dump can save the initial load and synchronization won't fetch much data from the server. The storage in the local IndexedDB is not a problem at all.
- But computing the signature on a big collection is costly and it's done every time there's a change. How costly?
- And if the use-case relies on the `RemotesSettings.get()` API, then the JEXL expession will be evaluated on the 1000 records. How costly? Caching is not trivial since the expressions may imply dates, randomness etc.

There might alternatives like creating segmented collections. Even it the server would be totally fine with it, in terms of operations monitoring, I don't think we'd want to have 170 collections like snippets-fr, snippets-de, snippets-en...

**Comment by leplatrem** [comment] 2019-03-21 11:23
I'm tempted to close this and bring it back if a use-case comes up. 

Feel free to re-open if you think I'm wrong

**Comment by ncloudioj** [comment] 2019-04-11 17:52
And we have a use case now :)

Activity Stream has various collections in Remote Settings ("cfr", "onboarding") that would like to have the server side filtering support, such as for l10n.

Equipped with this feature, our client can just fetch the messages for its locale without pulling down the whole messages sets.

**Comment by leplatrem** [comment] 2019-04-12 13:42
> Equipped with this feature, our client can just fetch the messages for their specific locale without pulling down the whole messages sets.

What's wrong with pulling down the whole messages sets? See the above questions...

Before adding more complexity, I continue to think that we haven't made the most of what we have...

Partial collection synchronization is available in kinto already. The problem is about signatures.
One theorical solution could be to pre-declare all the known subsets of the collection on the server.
```ini
# server.ini (or workspace collection metadata)
kinto.signer.main.cfr.partial_syncs = lang:fr
                                      lang:en
                                      lang:de
                                      lang:ca-ES
```

When changes are approved, the server would refresh the main signature (as usual) and compute a signature for each subset that was declared on the server. The metadata stores all the signatures.

```js
// buckets/main/collections/cfr
{
  "id": "cfr",
  "last_modified": 42,
  "signature": {
    "hash": "..."
  },
  "signatures": {
    "lang:en": {
      "hash": "..."
    },
    "lang:fr": {
      "hash": "..."
    },
    "lang:de": {
      "hash": "..."
    },
  },
}
```

And from the client side, it would mean something like this:
```js
await kintoClient.sync({ filters: { lang: "ca-ES" } });
```
And reading the appropriate signature from the metadata would mean picking the appropriate field:
```js 
let signature;
if (ObjectUtils.isEmpty(filters)) {
   signature = metadata.signature;
else {
   const key = filters.reduce(() => { ... }, "");
   signature = metadata.signatures[key];
} 
```

Among the immediate drawbacks of this approach:
* more complexity
* approving changes will compute a lot more signatures (and signature refresh etc.)
* the list of possible filters must be shared (and always in sync) between the clients and the server

**Comment by ncloudioj** [comment] 2019-04-12 17:53
> What's wrong with pulling down the whole messages sets? See the above questions...

Pulling down the whole message set seems a bit wasteful from application's perspective.

For instance, we have four messages in the CFR collection now (will definitely grow over time), let's say we fully localize them with all the locales and push them to Remote Settings. It'll easily run into that 1000 record situation soon. Also, CFR messages, currently 11KB, are relatively bigger in size than other collections. Intentionally, we'd like to not ship the dump so that we can completely control messages remotely (e.g. to end a CFR recommendation).  

As for client side filtering, from the previous experience of having one thousand records in Tippytop, it didn't scale as expected, and we ended up reducing the collection size to avoid the performance regression. This might not be the case if IndexedDB can fix the cursor iteration performance.

We understand that this feature would definitely add complexities to RS as mentioned above, let's see if we can find a best solution that works out on both side :)

**Closed** 2020-05-05 21:22 UTC
Labels: proposal
