### ISSUE TITLE
[Stage] Some Remote Settings pages return a blank page when accessed

### ISSUE THREAD

**Issue by heres-maria-sv-inactive** [mozilla/remote-settings#130] opened 2021-10-11 14:40 UTC
**[Prerequisites]:**
- Be connected to the corporate VPN.

**[Steps to reproduce]:**
1. Navigate to “https://settings-writer.stage.mozaws.net/v1/admin/#/buckets/main-workspace/collections/nimbus-desktop-experiments/simple-review ”.
2. Observe the page.

**[Expected result]:**
- The login prompt is displayed if not logged in and after login the page is displayed.

**[Actual result]:**
- The page is blank.

**[Notes]:**
- The first blank page observed was https://settings-writer.stage.mozaws.net/v1/admin/#/buckets/main-workspace/collections/, which now I can correctly open, but Simple Review seems to be again blank.
- The issue seems identical to #129, which for a while was no longer reproducible.
- Attached is a screen recording of the issue.

![RS 2](https://user-images.githubusercontent.com/53752296/136807396-2a3085ae-2197-4fd4-8121-bb31295bd425.gif)

**Comment by leplatrem** [comment] 2021-10-13 13:15
Thanks for reporting! We rolled back to the previous version, and will investigate

**Comment by leplatrem** [comment] 2021-10-19 14:59
This was fixed with the latest deploy!

**Closed as completed by leplatrem** 2021-10-19 14:59 UTC

**Comment by heres-maria** [comment] 2021-10-21 15:05
I have verified that the issue is no longer reproducible. I can now successfully access the Simple Review page without it being blank. Tested using Firefox Release 93.0 (Build ID: 20210927210923).
